import { Document } from "./types";

export const documents: Document[] = [
  {
    id: "1",
    name: "Annual Report 2025",
    category: "Report",
    type: "PDF",
    size: "2.4 MB",
    uploadDate: "2026-01-15",
    uploadedBy: "Sarah Johnson",
    tags: ["annual", "financial", "executive"],
    version: "v3.2",
    description: "Comprehensive annual report covering fiscal year 2025 performance metrics and strategic outlook.",
    status: "Active",
    createdAt: "2026-01-15",
  },
  {
    id: "2",
    name: "Q4 Sales Proposal",
    category: "Proposal",
    type: "DOCX",
    size: "1.8 MB",
    uploadDate: "2026-02-20",
    uploadedBy: "Michael Chen",
    tags: ["sales", "Q4", "proposal"],
    version: "v2.1",
    description: "Sales proposal for Q4 enterprise accounts including pricing tiers and implementation timeline.",
    status: "Active",
    createdAt: "2026-02-20",
  },
  {
    id: "3",
    name: "Employment Contract Template",
    category: "Contract",
    type: "PDF",
    size: "856 KB",
    uploadDate: "2026-03-05",
    uploadedBy: "Emily Rodriguez",
    tags: ["legal", "hr", "template"],
    version: "v5.0",
    description: "Standard employment contract template updated for 2026 compliance requirements.",
    status: "Active",
    createdAt: "2026-03-05",
  },
  {
    id: "4",
    name: "Marketing Brochure",
    category: "Marketing",
    type: "Image",
    size: "4.2 MB",
    uploadDate: "2026-03-12",
    uploadedBy: "Alex Thompson",
    tags: ["branding", "brochure", "print"],
    version: "v1.3",
    description: "Product marketing brochure with updated branding guidelines and product specifications.",
    status: "Active",
    createdAt: "2026-03-12",
  },
  {
    id: "5",
    name: "Invoice - Acme Corp",
    category: "Invoice",
    type: "PDF",
    size: "320 KB",
    uploadDate: "2026-04-01",
    uploadedBy: "Lisa Park",
    tags: ["invoice", "acme", "payment"],
    version: "v1.0",
    description: "Invoice for Acme Corp Q1 services - $45,000 due Net 30.",
    status: "Active",
    createdAt: "2026-04-01",
  },
  {
    id: "6",
    name: "Partnership Agreement - Globex",
    category: "Contract",
    type: "DOCX",
    size: "1.2 MB",
    uploadDate: "2026-04-18",
    uploadedBy: "David Kim",
    tags: ["legal", "partnership", "globex"],
    version: "v4.2",
    description: "Strategic partnership agreement between AOT and Globex Inc for joint go-to-market initiatives.",
    status: "Active",
    createdAt: "2026-04-18",
  },
  {
    id: "7",
    name: "R&D Expense Report",
    category: "Report",
    type: "XLSX",
    size: "980 KB",
    uploadDate: "2026-05-02",
    uploadedBy: "Sarah Johnson",
    tags: ["financial", "rd", "expenses"],
    version: "v2.0",
    description: "Detailed R&D expenditure breakdown for Q1 2026 with budget variance analysis.",
    status: "Active",
    createdAt: "2026-05-02",
  },
  {
    id: "8",
    name: "Q2 Investor Presentation",
    category: "Proposal",
    type: "PPTX",
    size: "6.7 MB",
    uploadDate: "2026-05-22",
    uploadedBy: "Michael Chen",
    tags: ["investor", "presentation", "Q2"],
    version: "v1.5",
    description: "Investor presentation covering Q2 2026 results, growth metrics, and forward guidance.",
    status: "Active",
    createdAt: "2026-05-22",
  },
  {
    id: "9",
    name: "Product Roadmap 2027",
    category: "Report",
    type: "PDF",
    size: "3.1 MB",
    uploadDate: "2026-06-10",
    uploadedBy: "Alex Thompson",
    tags: ["roadmap", "product", "planning"],
    version: "v0.9",
    description: "Preliminary product roadmap for 2027 with feature priorities and release timelines.",
    status: "Active",
    createdAt: "2026-06-10",
  },
  {
    id: "10",
    name: "Office Lease Agreement",
    category: "Contract",
    type: "PDF",
    size: "2.8 MB",
    uploadDate: "2025-11-15",
    uploadedBy: "Emily Rodriguez",
    tags: ["legal", "lease", "office"],
    version: "v3.0",
    description: "Office lease agreement for headquarters expansion - 5 year term with renewal options.",
    status: "Archived",
    createdAt: "2025-11-15",
  },
  {
    id: "11",
    name: "Old Brand Assets",
    category: "Marketing",
    type: "Image",
    size: "15.4 MB",
    uploadDate: "2025-09-28",
    uploadedBy: "Alex Thompson",
    tags: ["branding", "legacy", "assets"],
    version: "v1.0",
    description: "Legacy brand asset collection from previous branding agency - kept for reference.",
    status: "Archived",
    createdAt: "2025-09-28",
  },
  {
    id: "12",
    name: "Tax Filing 2025",
    category: "Invoice",
    type: "PDF",
    size: "5.6 MB",
    uploadDate: "2026-04-15",
    uploadedBy: "Lisa Park",
    tags: ["tax", "financial", "filing"],
    version: "v1.0",
    description: "Corporate tax filing documents for fiscal year 2025 with all supporting schedules.",
    status: "Active",
    createdAt: "2026-04-15",
  },
];