import {
  DollarSign,
  Users,
  Building2,
  Briefcase,
  Ticket,
} from "lucide-react";

import type {
  DashboardKPI,
  MonthlyRevenue,
  RecentActivity,
  RecentCustomer,
  RecentOpportunity,
  UpcomingTask,
  RecentCompany,
  Notification,
} from "./types";

export const kpis: DashboardKPI[] = [
  {
    title: "Total Revenue",
    value: "$284,500",
    change: 12.5,
    icon: DollarSign,
  },
  {
    title: "Customers",
    value: 1_248,
    change: 8.2,
    icon: Users,
  },
  {
    title: "Companies",
    value: 386,
    change: -2.4,
    icon: Building2,
  },
  {
    title: "Opportunities",
    value: 94,
    change: 16.1,
    icon: Briefcase,
  },
  {
    title: "Open Tickets",
    value: 23,
    change: -11.3,
    icon: Ticket,
  },
];

export const monthlyRevenue: MonthlyRevenue[] = [
  { month: "Jan", revenue: 18500, target: 20000 },
  { month: "Feb", revenue: 22300, target: 21000 },
  { month: "Mar", revenue: 19800, target: 22000 },
  { month: "Apr", revenue: 26200, target: 23000 },
  { month: "May", revenue: 24100, target: 24000 },
  { month: "Jun", revenue: 28900, target: 25000 },
  { month: "Jul", revenue: 31200, target: 26000 },
  { month: "Aug", revenue: 27500, target: 27000 },
  { month: "Sep", revenue: 29800, target: 28000 },
  { month: "Oct", revenue: 32100, target: 29000 },
  { month: "Nov", revenue: 29800, target: 30000 },
  { month: "Dec", revenue: 34200, target: 32000 },
];

export const recentActivities: RecentActivity[] = [
  {
    id: "1",
    type: "customer",
    action: "created",
    subject: "Acme Corporation was added as a new customer",
    timestamp: "2 minutes ago",
    user: "Sarah Chen",
  },
  {
    id: "2",
    type: "opportunity",
    action: "updated",
    subject: "Enterprise License Deal moved to Negotiation",
    timestamp: "15 minutes ago",
    user: "Michael Torres",
  },
  {
    id: "3",
    type: "ticket",
    action: "resolved",
    subject: "API integration timeout issue resolved",
    timestamp: "1 hour ago",
    user: "James Wilson",
  },
  {
    id: "4",
    type: "lead",
    action: "converted",
    subject: "TechStart Inc. converted from lead to opportunity",
    timestamp: "2 hours ago",
    user: "Emily Rodriguez",
  },
  {
    id: "5",
    type: "customer",
    action: "updated",
    subject: "GlobalTech Solutions contact info updated",
    timestamp: "3 hours ago",
    user: "David Kim",
  },
  {
    id: "6",
    type: "task",
    action: "completed",
    subject: "Q4 budget review meeting completed",
    timestamp: "5 hours ago",
    user: "Lisa Anderson",
  },
];

export const recentCustomers: RecentCustomer[] = [
  {
    id: "1",
    name: "Acme Corporation",
    company: "Acme Corp",
    email: "contact@acme.com",
    status: "Active",
    createdAt: "2026-07-25",
  },
  {
    id: "2",
    name: "TechStart Inc.",
    company: "TechStart",
    email: "info@techstart.io",
    status: "Prospect",
    createdAt: "2026-07-24",
  },
  {
    id: "3",
    name: "GlobalTech Solutions",
    company: "GlobalTech",
    email: "hello@globaltech.com",
    status: "Active",
    createdAt: "2026-07-22",
  },
  {
    id: "4",
    name: "NorthStar Analytics",
    company: "NorthStar",
    email: "team@northstar.ai",
    status: "Prospect",
    createdAt: "2026-07-21",
  },
  {
    id: "5",
    name: "BluePeak Software",
    company: "BluePeak",
    email: "sales@bluepeak.dev",
    status: "Active",
    createdAt: "2026-07-19",
  },
];

export const recentOpportunities: RecentOpportunity[] = [
  {
    id: "1",
    title: "Enterprise License Deal",
    customer: "Acme Corporation",
    value: 120000,
    stage: "Negotiation",
    probability: 70,
    createdAt: "2026-07-20",
  },
  {
    id: "2",
    title: "SaaS Platform Migration",
    customer: "TechStart Inc.",
    value: 85000,
    stage: "Proposal",
    probability: 50,
    createdAt: "2026-07-18",
  },
  {
    id: "3",
    title: "Infrastructure Consulting",
    customer: "GlobalTech Solutions",
    value: 45000,
    stage: "Discovery",
    probability: 30,
    createdAt: "2026-07-15",
  },
  {
    id: "4",
    title: "Data Analytics Suite",
    customer: "NorthStar Analytics",
    value: 95000,
    stage: "Qualification",
    probability: 20,
    createdAt: "2026-07-12",
  },
];

export const recentCompanies: RecentCompany[] = [
  {
    id: "1",
    name: "Acme Corporation",
    industry: "Technology",
    city: "San Francisco",
    country: "USA",
    status: "Active",
    createdAt: "2026-07-25",
  },
  {
    id: "2",
    name: "TechStart Inc.",
    industry: "Software",
    city: "Austin",
    country: "USA",
    status: "Active",
    createdAt: "2026-07-24",
  },
  {
    id: "3",
    name: "GlobalTech Solutions",
    industry: "Consulting",
    city: "London",
    country: "UK",
    status: "Active",
    createdAt: "2026-07-22",
  },
  {
    id: "4",
    name: "NorthStar Analytics",
    industry: "Analytics",
    city: "Toronto",
    country: "Canada",
    status: "Inactive",
    createdAt: "2026-07-21",
  },
  {
    id: "5",
    name: "BluePeak Software",
    industry: "Software",
    city: "Berlin",
    country: "Germany",
    status: "Active",
    createdAt: "2026-07-19",
  },
];

export const notifications: Notification[] = [
  {
    id: "1",
    type: "success",
    title: "Deal closed: Enterprise License",
    message: "Acme Corporation signed the enterprise license agreement worth $120,000.",
    timestamp: "10 minutes ago",
    read: false,
  },
  {
    id: "2",
    type: "warning",
    title: "SLA breach imminent",
    message: "Ticket #1023 'API timeout issue' is approaching its SLA deadline.",
    timestamp: "1 hour ago",
    read: false,
  },
  {
    id: "3",
    type: "info",
    title: "New lead assigned",
    message: "Lead 'DataSync Pro' from TechStart Inc. has been assigned to you.",
    timestamp: "2 hours ago",
    read: true,
  },
  {
    id: "4",
    type: "error",
    title: "System alert",
    message: "Email delivery failed for campaign 'Q3 Newsletter'. Review required.",
    timestamp: "3 hours ago",
    read: true,
  },
  {
    id: "5",
    type: "info",
    title: "Report ready",
    message: "Monthly sales report for June 2026 is now available for review.",
    timestamp: "5 hours ago",
    read: true,
  },
];

export const upcomingTasks: UpcomingTask[] = [
  {
    id: "1",
    title: "Review Q3 revenue forecast",
    dueDate: "2026-07-28",
    priority: "High",
    assignee: "Sarah Chen",
    completed: false,
  },
  {
    id: "2",
    title: "Follow up with TechStart proposal",
    dueDate: "2026-07-29",
    priority: "High",
    assignee: "Michael Torres",
    completed: false,
  },
  {
    id: "3",
    title: "Prepare monthly customer report",
    dueDate: "2026-07-30",
    priority: "Medium",
    assignee: "Emily Rodriguez",
    completed: false,
  },
  {
    id: "4",
    title: "Update opportunity pipeline",
    dueDate: "2026-07-31",
    priority: "Medium",
    assignee: "David Kim",
    completed: true,
  },
  {
    id: "5",
    title: "Team standup notes",
    dueDate: "2026-07-28",
    priority: "Low",
    assignee: "Lisa Anderson",
    completed: true,
  },
];
