import { Activity } from "./types";

export const activities: Activity[] = [
  {
    id: "1",
    type: "Meeting",
    subject: "Quarterly review with Acme Corp",
    description: "Discuss Q3 performance metrics and roadmap alignment.",
    date: "2026-07-28",
    time: "10:00",
    owner: "Alice Johnson",
    status: "Planned",
    relatedTo: "Acme Corp",
    relatedType: "customer",
    reminder: "15 minutes before",
    createdAt: "2026-07-20",
    updatedAt: "2026-07-25",
  },
  {
    id: "2",
    type: "Call",
    subject: "Follow-up on partnership proposal",
    description: "Call with Globex Inc about the joint venture terms.",
    date: "2026-07-27",
    time: "14:30",
    owner: "Bob Chen",
    status: "Planned",
    relatedTo: "Globex Inc",
    relatedType: "opportunity",
    reminder: "30 minutes before",
    createdAt: "2026-07-22",
    updatedAt: "2026-07-26",
  },
  {
    id: "3",
    type: "Email",
    subject: "Contract renewal sent to Initech",
    description: "Sent the annual maintenance contract for signature.",
    date: "2026-07-26",
    time: "09:15",
    owner: "Carol Davis",
    status: "Completed",
    relatedTo: "Initech Solutions",
    relatedType: "customer",
    reminder: "None",
    createdAt: "2026-07-26",
    updatedAt: "2026-07-26",
  },
  {
    id: "4",
    type: "Task",
    subject: "Prepare sales deck for Umbrella Health",
    description: "Create presentation for the upcoming product demo.",
    date: "2026-07-29",
    time: "17:00",
    owner: "David Lee",
    status: "In Progress",
    relatedTo: "Umbrella Health",
    relatedType: "lead",
    reminder: "1 day before",
    createdAt: "2026-07-24",
    updatedAt: "2026-07-27",
  },
  {
    id: "5",
    type: "Reminder",
    subject: "Visa renewal for international trip",
    description: "Ensure travel documents are updated before August.",
    date: "2026-08-01",
    time: "08:00",
    owner: "Eve Martin",
    status: "Planned",
    relatedTo: "Stark Defense",
    relatedType: "ticket",
    reminder: "2 days before",
    createdAt: "2026-07-18",
    updatedAt: "2026-07-23",
  },
  {
    id: "6",
    type: "Meeting",
    subject: "Sprint retrospective",
    description: "Team retro to review last sprint and plan improvements.",
    date: "2026-07-30",
    time: "11:00",
    owner: "Frank Wilson",
    status: "Planned",
    relatedTo: "Wayne Enterprises",
    relatedType: "customer",
    reminder: "15 minutes before",
    createdAt: "2026-07-21",
    updatedAt: "2026-07-28",
  },
  {
    id: "7",
    type: "Call",
    subject: "Support escalation call",
    description: "Address critical production issue reported by Cyberdyne.",
    date: "2026-07-27",
    time: "16:00",
    owner: "Grace Kim",
    status: "In Progress",
    relatedTo: "Cyberdyne Systems",
    relatedType: "ticket",
    reminder: "10 minutes before",
    createdAt: "2026-07-27",
    updatedAt: "2026-07-27",
  },
  {
    id: "8",
    type: "Email",
    subject: "Welcome email to new lead",
    description: "Sent onboarding materials and introduction to services.",
    date: "2026-07-25",
    time: "13:45",
    owner: "Henry Adams",
    status: "Completed",
    relatedTo: "Hooli Technologies",
    relatedType: "lead",
    reminder: "None",
    createdAt: "2026-07-25",
    updatedAt: "2026-07-25",
  },
  {
    id: "9",
    type: "Task",
    subject: "Audit compliance documents",
    description: "Review all regulatory filings for Q2.",
    date: "2026-07-28",
    time: "09:00",
    owner: "Ivy Brown",
    status: "Cancelled",
    relatedTo: "Pied Piper",
    relatedType: "opportunity",
    reminder: "1 day before",
    createdAt: "2026-07-15",
    updatedAt: "2026-07-26",
  },
  {
    id: "10",
    type: "Meeting",
    subject: "Monthly all-hands",
    description: "Company-wide update on strategy and milestones.",
    date: "2026-08-05",
    time: "15:00",
    owner: "Jack Taylor",
    status: "Planned",
    relatedTo: "Dunder Mifflin",
    relatedType: "customer",
    reminder: "1 hour before",
    createdAt: "2026-07-01",
    updatedAt: "2026-07-20",
  },
  {
    id: "11",
    type: "Reminder",
    subject: "Invoice due for Q3 subscription",
    description: "Payment of $12,500 is due for the enterprise license.",
    date: "2026-08-10",
    time: "12:00",
    owner: "Kara White",
    status: "Planned",
    relatedTo: "Massive Dynamic",
    relatedType: "customer",
    reminder: "3 days before",
    createdAt: "2026-07-10",
    updatedAt: "2026-07-28",
  },
  {
    id: "12",
    type: "Call",
    subject: "Discovery call with Soylent Corp",
    description: "Initial call to understand logistics needs.",
    date: "2026-07-26",
    time: "11:30",
    owner: "Leo Martinez",
    status: "Completed",
    relatedTo: "Soylent Corp",
    relatedType: "lead",
    reminder: "15 minutes before",
    createdAt: "2026-07-22",
    updatedAt: "2026-07-26",
  },
];
