import { Opportunity } from "./types";

export const opportunities: Opportunity[] = [
  {
    id: "1",
    title: "Enterprise Platform Upgrade",
    customer: "Acme Corp",
    value: 250000,
    stage: "Negotiation",
    probability: 75,
    expectedCloseDate: "2026-09-15",
    owner: "Alice Johnson",
    notes: "Finalizing contract terms with legal team.",
    status: "Open",
    createdAt: "2026-06-01",
    updatedAt: "2026-07-25",
  },
  {
    id: "2",
    title: "Cloud Migration Project",
    customer: "Globex Inc",
    value: 180000,
    stage: "Proposal",
    probability: 60,
    expectedCloseDate: "2026-10-01",
    owner: "Bob Chen",
    notes: "Proposal submitted, awaiting feedback.",
    status: "Open",
    createdAt: "2026-06-15",
    updatedAt: "2026-07-24",
  },
  {
    id: "3",
    title: "Data Analytics Suite",
    customer: "Initech Solutions",
    value: 95000,
    stage: "Qualification",
    probability: 30,
    expectedCloseDate: "2026-11-01",
    owner: "Carol Martinez",
    notes: "Initial discovery call completed.",
    status: "Open",
    createdAt: "2026-07-01",
    updatedAt: "2026-07-23",
  },
  {
    id: "4",
    title: "Security Audit & Compliance",
    customer: "Umbrella Health",
    value: 120000,
    stage: "Discovery",
    probability: 20,
    expectedCloseDate: "2026-12-01",
    owner: "David Lee",
    notes: "Gathering requirements for audit scope.",
    status: "Open",
    createdAt: "2026-07-10",
    updatedAt: "2026-07-22",
  },
  {
    id: "5",
    title: "Infrastructure Modernization",
    customer: "Stark Defense",
    value: 500000,
    stage: "Negotiation",
    probability: 80,
    expectedCloseDate: "2026-08-30",
    owner: "Alice Johnson",
    notes: "Contract review in progress.",
    status: "Open",
    createdAt: "2026-05-01",
    updatedAt: "2026-07-25",
  },
  {
    id: "6",
    title: "AI Chatbot Integration",
    customer: "Wayne Enterprises",
    value: 75000,
    stage: "Closed Won",
    probability: 100,
    expectedCloseDate: "2026-07-15",
    owner: "Bob Chen",
    notes: "Deal closed. Implementation starts August.",
    status: "Won",
    createdAt: "2026-04-10",
    updatedAt: "2026-07-15",
  },
  {
    id: "7",
    title: "Managed Services Contract",
    customer: "Cyberdyne Systems",
    value: 320000,
    stage: "Proposal",
    probability: 55,
    expectedCloseDate: "2026-10-15",
    owner: "Carol Martinez",
    notes: "Drafting SOW for review.",
    status: "Open",
    createdAt: "2026-06-20",
    updatedAt: "2026-07-21",
  },
  {
    id: "8",
    title: "CRM Implementation",
    customer: "Hooli Technologies",
    value: 150000,
    stage: "Qualification",
    probability: 35,
    expectedCloseDate: "2026-11-15",
    owner: "David Lee",
    notes: "Scheduling demo for next week.",
    status: "Open",
    createdAt: "2026-07-05",
    updatedAt: "2026-07-20",
  },
  {
    id: "9",
    title: "DevOps Toolchain Setup",
    customer: "Pied Piper",
    value: 45000,
    stage: "Closed Lost",
    probability: 0,
    expectedCloseDate: "2026-06-30",
    owner: "Alice Johnson",
    notes: "Customer chose in-house solution.",
    status: "Lost",
    createdAt: "2026-05-15",
    updatedAt: "2026-06-30",
  },
  {
    id: "10",
    title: "Paperless Office Solution",
    customer: "Dunder Mifflin",
    value: 28000,
    stage: "Proposal",
    probability: 65,
    expectedCloseDate: "2026-09-01",
    owner: "Bob Chen",
    notes: "Proposal sent, follow-up scheduled.",
    status: "Open",
    createdAt: "2026-07-08",
    updatedAt: "2026-07-19",
  },
  {
    id: "11",
    title: "R&D Partnership Program",
    customer: "Massive Dynamic",
    value: 600000,
    stage: "Discovery",
    probability: 15,
    expectedCloseDate: "2026-12-15",
    owner: "Carol Martinez",
    notes: "Initial exploratory meeting held.",
    status: "Open",
    createdAt: "2026-07-12",
    updatedAt: "2026-07-18",
  },
  {
    id: "12",
    title: "Supply Chain Automation",
    customer: "Soylent Corp",
    value: 210000,
    stage: "Negotiation",
    probability: 70,
    expectedCloseDate: "2026-09-30",
    owner: "David Lee",
    notes: "Negotiating pricing and delivery terms.",
    status: "Open",
    createdAt: "2026-06-05",
    updatedAt: "2026-07-25",
  },
];
