-- Add fields to Company
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "size" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "revenue" TEXT;

-- Add fields to Contact
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "tags" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'Active';

-- Add fields to Lead
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "probability" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "expectedRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "tags" JSONB NOT NULL DEFAULT '[]';

-- Add fields to Opportunity
ALTER TABLE "Opportunity" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'Open';

-- Add fields to Ticket
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "sla" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "requester" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "comments" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "attachments" INTEGER NOT NULL DEFAULT 0;

-- Add fields to Document
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "tags" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "version" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'Active';
