import { Report } from "./types";

export const reports: Report[] = [
  {
    id: "1",
    name: "Monthly Sales Overview",
    category: "Sales",
    type: "Bar Chart",
    description: "Aggregated sales performance across all regions for the current month.",
    createdBy: "Alice Johnson",
    createdAt: "2026-01-10",
    lastRun: "2026-07-25",
    status: "Published",
  },
  {
    id: "2",
    name: "Customer Acquisition Trends",
    category: "Customer",
    type: "Line Chart",
    description: "New customer sign-ups tracked weekly over the past quarter.",
    createdBy: "Bob Chen",
    createdAt: "2026-02-14",
    lastRun: "2026-07-24",
    status: "Published",
  },
  {
    id: "3",
    name: "Deal Pipeline Funnel",
    category: "Pipeline",
    type: "Pie Chart",
    description: "Visual breakdown of deals by stage in the sales pipeline.",
    createdBy: "Carol Martinez",
    createdAt: "2026-03-01",
    lastRun: "2026-07-23",
    status: "Published",
  },
  {
    id: "4",
    name: "Quarterly Revenue Report",
    category: "Financial",
    type: "Summary",
    description: "Revenue totals and growth metrics for Q2 2026.",
    createdBy: "David Lee",
    createdAt: "2026-04-05",
    lastRun: "2026-07-22",
    status: "Published",
  },
  {
    id: "5",
    name: "Support Ticket Activity",
    category: "Activity",
    type: "Line Chart",
    description: "Daily ticket volume and resolution times for the support team.",
    createdBy: "Emma Wilson",
    createdAt: "2026-04-18",
    lastRun: "2026-07-21",
    status: "Published",
  },
  {
    id: "6",
    name: "Custom Campaign Analysis",
    category: "Custom",
    type: "Bar Chart",
    description: "Performance metrics for the Q2 email and social campaigns.",
    createdBy: "Frank Brown",
    createdAt: "2026-05-10",
    lastRun: "2026-07-20",
    status: "Draft",
  },
  {
    id: "7",
    name: "Customer Churn Analysis",
    category: "Customer",
    type: "Table",
    description: "List of at-risk accounts and churn indicators.",
    createdBy: "Grace Kim",
    createdAt: "2026-05-22",
    lastRun: "2026-07-19",
    status: "Published",
  },
  {
    id: "8",
    name: "Sales Rep Performance",
    category: "Sales",
    type: "Bar Chart",
    description: "Individual quota attainment and deal close rates by rep.",
    createdBy: "Henry Davis",
    createdAt: "2026-06-01",
    lastRun: "2026-07-18",
    status: "Published",
  },
  {
    id: "9",
    name: "Lead Conversion Report",
    category: "Pipeline",
    type: "Table",
    description: "Lead-to-opportunity conversion rates by source.",
    createdBy: "Iris Patel",
    createdAt: "2026-06-15",
    lastRun: "2026-07-17",
    status: "Draft",
  },
  {
    id: "10",
    name: "Expense Breakdown",
    category: "Financial",
    type: "Pie Chart",
    description: "Departmental spend distribution for the current fiscal year.",
    createdBy: "Jack Thompson",
    createdAt: "2026-06-20",
    lastRun: "2026-07-16",
    status: "Published",
  },
  {
    id: "11",
    name: "Weekly Activity Log",
    category: "Activity",
    type: "Summary",
    description: "Weekly summary of calls, emails, and meetings logged.",
    createdBy: "Kate Anderson",
    createdAt: "2026-07-01",
    lastRun: "2026-07-15",
    status: "Draft",
  },
  {
    id: "12",
    name: "Ad-hoc Query Report",
    category: "Custom",
    type: "Table",
    description: "One-time data export filtered by custom parameters.",
    createdBy: "Leo Garcia",
    createdAt: "2026-07-10",
    lastRun: "2026-07-14",
    status: "Archived",
  },
];
