import { CustomerService } from "./customer.service";
import { CompanyService } from "./company.service";
import { ContactService } from "./contact.service";
import { LeadService } from "./lead.service";
import { OpportunityService } from "./opportunity.service";
import { ActivityService } from "./activity.service";
import { TicketService } from "./ticket.service";
import { DocumentService } from "./document.service";

import { customers as initialCustomers } from "@/app/(app)/customers/data";
import { companies as initialCompanies } from "@/app/(app)/companies/data";
import { contacts as initialContacts } from "@/app/(app)/contacts/data";
import { leads as initialLeads } from "@/app/(app)/leads/data";
import { opportunities as initialOpportunities } from "@/app/(app)/opportunities/data";
import { activities as initialActivities } from "@/app/(app)/activities/data";
import { tickets as initialTickets } from "@/app/(app)/tickets/data";
import { documents as initialDocuments } from "@/app/(app)/documents/data";

export const customerService = new CustomerService(initialCustomers);
export const companyService = new CompanyService(initialCompanies);
export const contactService = new ContactService(initialContacts);
export const leadService = new LeadService(initialLeads);
export const opportunityService = new OpportunityService(initialOpportunities);
export const activityService = new ActivityService(initialActivities);
export const ticketService = new TicketService(initialTickets);
export const documentService = new DocumentService(initialDocuments);

export { auditService } from "./audit.service";
export { graphService } from "./graph.service";
export { favoritesService } from "./favorites.service";
export { recentlyViewedService } from "./recently-viewed.service";
export { globalSearchService } from "./global-search.service";
export { outlookService } from "./outlook.service";
export { calendarService } from "./calendar.service";
export { teamsService } from "./teams.service";
export { zoomService } from "./zoom.service";
export { fileManagementService } from "./file-management.service";
export { noteService } from "./note.service";
export { remindersService } from "./reminders.service";
export { assignmentsService } from "./assignments.service";
export { eventBus } from "./event-bus";
export { Events } from "./events";
export { synchronizedActivityService } from "./synchronized-activity.service";
export { synchronizedNotificationService } from "./synchronized-notification.service";
export { ensureEventWiring } from "./event-wiring";
