import { Company } from "./types";

export const companies: Company[] = [
  {
    id: "1",
    name: "Acme Corp",
    industry: "Technology",
    size: "500+",
    address: "123 Innovation Drive",
    city: "San Francisco",
    country: "USA",
    website: "https://acmecorp.com",
    email: "contact@acmecorp.com",
    phone: "+1 555-0101",
    employeeCount: 12500,
    revenue: "$4.2B",
    status: "Active",
    createdAt: "2024-01-15",
    updatedAt: "2026-07-20",
  },
  {
    id: "2",
    name: "Globex Inc",
    industry: "Manufacturing",
    size: "201-500",
    address: "456 Industrial Blvd",
    city: "Chicago",
    country: "USA",
    website: "https://globex.com",
    email: "info@globex.com",
    phone: "+1 555-0102",
    employeeCount: 3400,
    revenue: "$1.8B",
    status: "Active",
    createdAt: "2024-03-22",
    updatedAt: "2026-07-19",
  },
  {
    id: "3",
    name: "Initech Solutions",
    industry: "Technology",
    size: "51-200",
    address: "789 Tech Park",
    city: "Austin",
    country: "USA",
    website: "https://initech.io",
    email: "hello@initech.io",
    phone: "+1 555-0103",
    employeeCount: 180,
    revenue: "$890M",
    status: "Active",
    createdAt: "2024-06-10",
    updatedAt: "2026-07-18",
  },
  {
    id: "4",
    name: "Umbrella Health",
    industry: "Healthcare",
    size: "500+",
    address: "321 Medical Plaza",
    city: "Boston",
    country: "USA",
    website: "https://umbrellahealth.com",
    email: "support@umbrellahealth.com",
    phone: "+1 555-0104",
    employeeCount: 28000,
    revenue: "$3.1B",
    status: "Active",
    createdAt: "2023-11-05",
    updatedAt: "2026-07-17",
  },
  {
    id: "5",
    name: "Stark Defense",
    industry: "Defense",
    size: "500+",
    address: "1 Stark Tower",
    city: "New York",
    country: "USA",
    website: "https://starkdefense.com",
    email: "contracts@starkdefense.com",
    phone: "+1 555-0105",
    employeeCount: 45000,
    revenue: "$6.5B",
    status: "Active",
    createdAt: "2023-08-12",
    updatedAt: "2026-07-16",
  },
  {
    id: "6",
    name: "Wayne Enterprises",
    industry: "Technology",
    size: "500+",
    address: "1007 Mountain Drive",
    city: "Gotham",
    country: "USA",
    website: "https://wayneent.com",
    email: "info@wayneent.com",
    phone: "+1 555-0106",
    employeeCount: 32000,
    revenue: "$5.2B",
    status: "Active",
    createdAt: "2023-05-20",
    updatedAt: "2026-07-15",
  },
  {
    id: "7",
    name: "Cyberdyne Systems",
    industry: "Technology",
    size: "201-500",
    address: "500 AI Avenue",
    city: "Los Angeles",
    country: "USA",
    website: "https://cyberdyne.ai",
    email: "lab@cyberdyne.ai",
    phone: "+1 555-0107",
    employeeCount: 4800,
    revenue: "$2.4B",
    status: "Active",
    createdAt: "2024-09-01",
    updatedAt: "2026-07-14",
  },
  {
    id: "8",
    name: "Hooli Technologies",
    industry: "Technology",
    size: "500+",
    address: "1 Hooli Plaza",
    city: "Silicon Valley",
    country: "USA",
    website: "https://hooli.xyz",
    email: "press@hooli.xyz",
    phone: "+1 555-0108",
    employeeCount: 15000,
    revenue: "$1.5B",
    status: "Active",
    createdAt: "2024-02-14",
    updatedAt: "2026-07-13",
  },
  {
    id: "9",
    name: "Pied Piper",
    industry: "Technology",
    size: "11-50",
    address: "42 Piedmont Avenue",
    city: "San Francisco",
    country: "USA",
    website: "https://piedpiper.com",
    email: "team@piedpiper.com",
    phone: "+1 555-0109",
    employeeCount: 35,
    revenue: "$120M",
    status: "Inactive",
    createdAt: "2025-01-10",
    updatedAt: "2026-07-12",
  },
  {
    id: "10",
    name: "Dunder Mifflin",
    industry: "Paper",
    size: "51-200",
    address: "1725 Slough Avenue",
    city: "Scranton",
    country: "USA",
    website: "https://dundermifflin.com",
    email: "sales@dundermifflin.com",
    phone: "+1 555-0110",
    employeeCount: 120,
    revenue: "$70M",
    status: "Active",
    createdAt: "2023-03-15",
    updatedAt: "2026-07-11",
  },
  {
    id: "11",
    name: "Massive Dynamic",
    industry: "Technology",
    size: "500+",
    address: "200 Vesey Street",
    city: "New York",
    country: "USA",
    website: "https://massivedynamic.com",
    email: "research@massivedynamic.com",
    phone: "+1 555-0111",
    employeeCount: 18000,
    revenue: "$900M",
    status: "Inactive",
    createdAt: "2024-07-04",
    updatedAt: "2026-07-10",
  },
  {
    id: "12",
    name: "Soylent Corp",
    industry: "Food",
    size: "201-500",
    address: "789 Green Street",
    city: "Chicago",
    country: "USA",
    website: "https://soylent.com",
    email: "hello@soylent.com",
    phone: "+1 555-0112",
    employeeCount: 2500,
    revenue: "$450M",
    status: "Inactive",
    createdAt: "2024-10-28",
    updatedAt: "2026-07-09",
  },
];
