export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",

  SALES_MANAGER = "SALES_MANAGER",
  SALES = "SALES",

  SUPPORT_MANAGER = "SUPPORT_MANAGER",
  SUPPORT = "SUPPORT",

  HR_MANAGER = "HR_MANAGER",
  HR = "HR",

  VIEWER = "VIEWER",
}