import { Contact } from "./types";

export const contacts: Contact[] = [
  {
    id: "1",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@microsoft.com",
    phone: "+1 555-0101",
    position: "Software Engineer",
    company: "Microsoft",
    country: "USA",
    city: "Seattle",
    notes: "Lead engineer on Azure team.",
    tags: ["engineering", "azure"],
    status: "Active",
    createdAt: "2026-07-01",
    updatedAt: "2026-07-20",
  },
  {
    id: "2",
    firstName: "Bob",
    lastName: "Smith",
    email: "bob.smith@google.com",
    phone: "+1 555-0102",
    position: "Product Manager",
    company: "Google",
    country: "USA",
    city: "Mountain View",
    notes: "Oversees Google Workspace.",
    tags: ["product", "workspace"],
    status: "Active",
    createdAt: "2026-07-02",
    updatedAt: "2026-07-21",
  },
  {
    id: "3",
    firstName: "Carol",
    lastName: "Davis",
    email: "carol.davis@amazon.com",
    phone: "+1 555-0103",
    position: "UX Designer",
    company: "Amazon",
    country: "USA",
    city: "Seattle",
    notes: "Works on AWS console UX.",
    tags: ["design", "aws"],
    status: "Active",
    createdAt: "2026-07-03",
    updatedAt: "2026-07-22",
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@apple.com",
    phone: "+1 555-0104",
    position: "iOS Developer",
    company: "Apple",
    country: "USA",
    city: "Cupertino",
    notes: "Core iOS frameworks.",
    tags: ["engineering", "ios"],
    status: "Active",
    createdAt: "2026-07-04",
    updatedAt: "2026-07-23",
  },
  {
    id: "5",
    firstName: "Eve",
    lastName: "Martinez",
    email: "eve.martinez@meta.com",
    phone: "+1 555-0105",
    position: "Data Scientist",
    company: "Meta",
    country: "USA",
    city: "Menlo Park",
    notes: "AI/ML research team.",
    tags: ["data", "ai"],
    status: "Active",
    createdAt: "2026-07-05",
    updatedAt: "2026-07-24",
  },
  {
    id: "6",
    firstName: "Frank",
    lastName: "Brown",
    email: "frank.brown@netflix.com",
    phone: "+1 555-0106",
    position: "DevOps Engineer",
    company: "Netflix",
    country: "USA",
    city: "Los Gatos",
    notes: "Streaming infrastructure.",
    tags: ["engineering", "devops"],
    status: "Inactive",
    createdAt: "2026-07-06",
    updatedAt: "2026-07-25",
  },
  {
    id: "7",
    firstName: "Grace",
    lastName: "Lee",
    email: "grace.lee@tesla.com",
    phone: "+1 555-0107",
    position: "Autopilot Engineer",
    company: "Tesla",
    country: "USA",
    city: "Austin",
    notes: "Computer vision team.",
    tags: ["engineering", "autopilot"],
    status: "Active",
    createdAt: "2026-07-07",
    updatedAt: "2026-07-26",
  },
  {
    id: "8",
    firstName: "Henry",
    lastName: "Garcia",
    email: "henry.garcia@spotify.com",
    phone: "+1 555-0108",
    position: "Backend Developer",
    company: "Spotify",
    country: "Sweden",
    city: "Stockholm",
    notes: "Music recommendation engine.",
    tags: ["engineering", "backend"],
    status: "Active",
    createdAt: "2026-07-08",
    updatedAt: "2026-07-27",
  },
  {
    id: "9",
    firstName: "Ivy",
    lastName: "Chen",
    email: "ivy.chen@stripe.com",
    phone: "+1 555-0109",
    position: "Security Analyst",
    company: "Stripe",
    country: "USA",
    city: "San Francisco",
    notes: "Payment security & compliance.",
    tags: ["security", "compliance"],
    status: "Active",
    createdAt: "2026-07-09",
    updatedAt: "2026-07-28",
  },
  {
    id: "10",
    firstName: "Jack",
    lastName: "Taylor",
    email: "jack.taylor@airbnb.com",
    phone: "+1 555-0110",
    position: "Frontend Developer",
    company: "Airbnb",
    country: "USA",
    city: "San Francisco",
    notes: "Design system team.",
    tags: ["engineering", "frontend"],
    status: "Inactive",
    createdAt: "2026-07-10",
    updatedAt: "2026-07-29",
  },
  {
    id: "11",
    firstName: "Karen",
    lastName: "White",
    email: "karen.white@shopify.com",
    phone: "+1 555-0111",
    position: "Marketing Lead",
    company: "Shopify",
    country: "Canada",
    city: "Ottawa",
    notes: "E-commerce marketing.",
    tags: ["marketing", "ecommerce"],
    status: "Active",
    createdAt: "2026-07-11",
    updatedAt: "2026-07-30",
  },
  {
    id: "12",
    firstName: "Leo",
    lastName: "Harris",
    email: "leo.harris@datadog.com",
    phone: "+1 555-0112",
    position: "Site Reliability Engineer",
    company: "Datadog",
    country: "USA",
    city: "New York",
    notes: "Monitoring infrastructure.",
    tags: ["engineering", "sre"],
    status: "Active",
    createdAt: "2026-07-12",
    updatedAt: "2026-07-31",
  },
];
