import { Lead } from "./types";

export const leads: Lead[] = [
  {
    id: "1",
    title: "ERP Implementation",
    company: "Acme Corp",
    contactName: "John Smith",
    email: "john@acmecorp.com",
    phone: "+1 555-0101",
    source: "Website",
    score: 85,
    probability: 70,
    owner: "Alice Johnson",
    expectedRevenue: 250000,
    status: "Qualified",
    notes: "Interested in full ERP suite with custom modules.",
    createdAt: "2026-06-10",
    updatedAt: "2026-07-25",
  },
  {
    id: "2",
    title: "Cloud Migration",
    company: "Globex Inc",
    contactName: "Sarah Lee",
    email: "sarah@globex.com",
    phone: "+1 555-0102",
    source: "Referral",
    score: 92,
    probability: 85,
    owner: "Bob Chen",
    expectedRevenue: 180000,
    status: "Proposal",
    notes: "Existing client referral. Needs hybrid cloud setup.",
    createdAt: "2026-06-15",
    updatedAt: "2026-07-24",
  },
  {
    id: "3",
    title: "Data Analytics Platform",
    company: "Initech Solutions",
    contactName: "Mike Wilson",
    email: "mike@initech.io",
    phone: "+1 555-0103",
    source: "LinkedIn",
    score: 45,
    probability: 30,
    owner: "Alice Johnson",
    expectedRevenue: 120000,
    status: "Contacted",
    notes: "Initial meeting scheduled for next week.",
    createdAt: "2026-06-20",
    updatedAt: "2026-07-23",
  },
  {
    id: "4",
    title: "Cyber Security Audit",
    company: "Umbrella Health",
    contactName: "Emily Davis",
    email: "emily@umbrellahealth.com",
    phone: "+1 555-0104",
    source: "Conference",
    score: 78,
    probability: 60,
    owner: "Diana Park",
    expectedRevenue: 95000,
    status: "Qualified",
    notes: "Met at HealthTech conference. Compliance-focused.",
    createdAt: "2026-06-25",
    updatedAt: "2026-07-22",
  },
  {
    id: "5",
    title: "AI Assistant Integration",
    company: "Stark Defense",
    contactName: "Tony Rhodes",
    email: "t.rhodes@starkdefense.com",
    phone: "+1 555-0105",
    source: "Cold Call",
    score: 30,
    probability: 15,
    owner: "Bob Chen",
    expectedRevenue: 350000,
    status: "New",
    notes: "Gatekeeper screened. Sent brochure via email.",
    createdAt: "2026-07-01",
    updatedAt: "2026-07-21",
  },
  {
    id: "6",
    title: "Smart Factory Solution",
    company: "Wayne Enterprises",
    contactName: "Lucius Fox",
    email: "l.fox@wayneent.com",
    phone: "+1 555-0106",
    source: "Referral",
    score: 95,
    probability: 90,
    owner: "Alice Johnson",
    expectedRevenue: 500000,
    status: "Negotiation",
    notes: "Contract review in progress. Legal team engaged.",
    createdAt: "2026-05-10",
    updatedAt: "2026-07-26",
  },
  {
    id: "7",
    title: "Machine Learning Pipeline",
    company: "Cyberdyne Systems",
    contactName: "Miles Dyson",
    email: "m.dyson@cyberdyne.ai",
    phone: "+1 555-0107",
    source: "Website",
    score: 60,
    probability: 45,
    owner: "Diana Park",
    expectedRevenue: 210000,
    status: "Contacted",
    notes: "Requested technical whitepaper and case studies.",
    createdAt: "2026-07-05",
    updatedAt: "2026-07-20",
  },
  {
    id: "8",
    title: "DevOps Transformation",
    company: "Hooli Technologies",
    contactName: "Nelson Bighetti",
    email: "bighetti@hooli.xyz",
    phone: "+1 555-0108",
    source: "Conference",
    score: 70,
    probability: 55,
    owner: "Bob Chen",
    expectedRevenue: 175000,
    status: "Qualified",
    notes: "Follow-up from Tech Summit. Budget approved.",
    createdAt: "2026-07-08",
    updatedAt: "2026-07-19",
  },
  {
    id: "9",
    title: "Network Infrastructure Upgrade",
    company: "Pied Piper",
    contactName: "Richard Hendricks",
    email: "richard@piedpiper.com",
    phone: "+1 555-0109",
    source: "LinkedIn",
    score: 15,
    probability: 10,
    owner: "Alice Johnson",
    expectedRevenue: 60000,
    status: "New",
    notes: "Early stage. Not sure about budget yet.",
    createdAt: "2026-07-12",
    updatedAt: "2026-07-18",
  },
  {
    id: "10",
    title: "Document Management System",
    company: "Dunder Mifflin",
    contactName: "Michael Scott",
    email: "m.scott@dundermifflin.com",
    phone: "+1 555-0110",
    source: "Other",
    score: 40,
    probability: 25,
    owner: "Diana Park",
    expectedRevenue: 45000,
    status: "Contacted",
    notes: "Referred by regional partner. Demo scheduled.",
    createdAt: "2026-07-14",
    updatedAt: "2026-07-17",
  },
  {
    id: "11",
    title: "Quantum Computing Research",
    company: "Massive Dynamic",
    contactName: "Walter Bishop",
    email: "w.bishop@massivedynamic.com",
    phone: "+1 555-0111",
    source: "Website",
    score: 88,
    probability: 75,
    owner: "Bob Chen",
    expectedRevenue: 420000,
    status: "Negotiation",
    notes: "NDA signed. Scope of work being finalized.",
    createdAt: "2026-05-20",
    updatedAt: "2026-07-26",
  },
  {
    id: "12",
    title: "Inventory Management",
    company: "Soylent Corp",
    contactName: "Henry Ford",
    email: "h.ford@soylent.com",
    phone: "+1 555-0112",
    source: "Cold Call",
    score: 55,
    probability: 40,
    owner: "Alice Johnson",
    expectedRevenue: 88000,
    status: "New",
    notes: "Cold outreach. Plant manager showed interest.",
    createdAt: "2026-07-15",
    updatedAt: "2026-07-16",
  },
];
