import { Company } from "./types";

export const companies: Company[] = [
  {
    id: 1,
    companyName: "Ascend One Tech",
    industry: "Information Technology",
    website: "https://ascendonetech.com",
    email: "info@ascendonetech.com",
    phone: "+63 2 8123 4567",
    country: "Philippines",
    city: "Quezon City",
    address: "Quezon City, Metro Manila",
    employeeCount: 250,
    status: "Active",
    createdAt: "2026-01-15",
  },
  {
    id: 2,
    companyName: "ABC Corporation",
    industry: "Finance",
    website: "https://abc.com",
    email: "contact@abc.com",
    phone: "+63 2 8234 5678",
    country: "Philippines",
    city: "Makati",
    address: "Ayala Avenue, Makati",
    employeeCount: 120,
    status: "Active",
    createdAt: "2026-02-10",
  },
  {
    id: 3,
    companyName: "XYZ Solutions",
    industry: "Consulting",
    website: "https://xyzsolutions.com",
    email: "hello@xyzsolutions.com",
    phone: "+63 2 8345 6789",
    country: "Singapore",
    city: "Singapore",
    address: "Marina Bay",
    employeeCount: 85,
    status: "Inactive",
    createdAt: "2026-03-01",
  },
];