import { Ticket } from "./types";

export const tickets: Ticket[] = [
  {
    id: "1",
    subject: "Login page returns 500 error",
    description: "Users are unable to log in after the latest deployment. The login endpoint returns a 500 internal server error.",
    priority: "Critical",
    status: "In Progress",
    sla: "4h",
    assignee: "Alice Chen",
    requester: "Bob Martinez",
    department: "Engineering",
    comments: 8,
    attachments: 2,
    createdAt: "2026-07-26",
    updatedAt: "2026-07-27",
  },
  {
    id: "2",
    subject: "Invoice PDF generation fails",
    description: "PDF invoices for international customers are not generating correctly. Currency symbols are garbled.",
    priority: "High",
    status: "Open",
    sla: "8h",
    assignee: "David Kim",
    requester: "Sarah Johnson",
    department: "Finance",
    comments: 3,
    attachments: 1,
    createdAt: "2026-07-26",
    updatedAt: "2026-07-27",
  },
  {
    id: "3",
    subject: "Update onboarding wizard copy",
    description: "The onboarding wizard text needs to be updated per the latest marketing guidelines. New copy attached.",
    priority: "Low",
    status: "Resolved",
    sla: "1 week",
    assignee: "Emily Davis",
    requester: "James Wilson",
    department: "Marketing",
    comments: 5,
    attachments: 3,
    createdAt: "2026-07-24",
    updatedAt: "2026-07-27",
  },
  {
    id: "4",
    subject: "Database connection pool exhausted",
    description: "Production database is hitting connection pool limits under heavy load. Need to increase pool size or optimize queries.",
    priority: "Critical",
    status: "In Progress",
    sla: "4h",
    assignee: "David Kim",
    requester: "Alice Chen",
    department: "Engineering",
    comments: 12,
    attachments: 0,
    createdAt: "2026-07-26",
    updatedAt: "2026-07-27",
  },
  {
    id: "5",
    subject: "User profile avatar upload broken",
    description: "Users cannot upload new profile pictures. The media upload service returns a 413 error for files under the limit.",
    priority: "Medium",
    status: "Open",
    sla: "24h",
    assignee: "Frank Lee",
    requester: "Linda Thompson",
    department: "Engineering",
    comments: 4,
    attachments: 1,
    createdAt: "2026-07-25",
    updatedAt: "2026-07-26",
  },
  {
    id: "6",
    subject: "Quarterly tax report export error",
    description: "The tax report export for Q2 2026 is missing several transactions. Data integrity issue in the reporting module.",
    priority: "High",
    status: "Open",
    sla: "8h",
    assignee: "Emily Davis",
    requester: "Robert Brown",
    department: "Finance",
    comments: 6,
    attachments: 2,
    createdAt: "2026-07-25",
    updatedAt: "2026-07-26",
  },
  {
    id: "7",
    subject: "Add dark mode support",
    description: "Customer requested dark mode support for the dashboard. Need to implement theme toggle and dark color scheme.",
    priority: "Low",
    status: "Closed",
    sla: "1 week",
    assignee: "Frank Lee",
    requester: "Grace Kim",
    department: "Product",
    comments: 15,
    attachments: 0,
    createdAt: "2026-07-20",
    updatedAt: "2026-07-26",
  },
  {
    id: "8",
    subject: "Email notification delay in staging",
    description: "Staging environment email notifications are arriving 10-15 minutes late. SMTP relay configuration may need adjustment.",
    priority: "Medium",
    status: "Resolved",
    sla: "24h",
    assignee: "Alice Chen",
    requester: "Henry Ford",
    department: "Engineering",
    comments: 7,
    attachments: 1,
    createdAt: "2026-07-24",
    updatedAt: "2026-07-26",
  },
  {
    id: "9",
    subject: "API rate limiting too aggressive",
    description: "Third-party integrators are hitting rate limits at 100 req/min. Need to increase to 300 req/min for enterprise tier.",
    priority: "High",
    status: "In Progress",
    sla: "8h",
    assignee: "David Kim",
    requester: "Sarah Johnson",
    department: "Engineering",
    comments: 9,
    attachments: 0,
    createdAt: "2026-07-25",
    updatedAt: "2026-07-27",
  },
  {
    id: "10",
    subject: "Mobile responsive layout broken on iOS",
    description: "The dashboard grid layout overlaps on iOS Safari. Flexbox gap not rendering correctly in older Safari versions.",
    priority: "Medium",
    status: "Open",
    sla: "48h",
    assignee: "Frank Lee",
    requester: "Isabel Garcia",
    department: "Engineering",
    comments: 2,
    attachments: 3,
    createdAt: "2026-07-26",
    updatedAt: "2026-07-27",
  },
  {
    id: "11",
    subject: "Update privacy policy page",
    description: "Legal team has provided updated privacy policy text to comply with new EU regulations. Update the static page content.",
    priority: "Low",
    status: "Open",
    sla: "1 week",
    assignee: "Emily Davis",
    requester: "Kevin Patel",
    department: "Legal",
    comments: 1,
    attachments: 2,
    createdAt: "2026-07-27",
    updatedAt: "2026-07-27",
  },
  {
    id: "12",
    subject: "Search index stuck in rebuild loop",
    description: "Elasticsearch index is stuck in a continuous rebuild cycle. Primary shard allocation failure on node 3.",
    priority: "Critical",
    status: "Open",
    sla: "4h",
    assignee: "David Kim",
    requester: "Alice Chen",
    department: "Engineering",
    comments: 18,
    attachments: 0,
    createdAt: "2026-07-27",
    updatedAt: "2026-07-27",
  },
];
