import { Customer } from "./types";

export const customers: Customer[] = [
  {
    id: "1",
    name: "John Smith",
    company: "Microsoft",
    email: "john.smith@microsoft.com",
    phone: "+1 555-1000",
    position: "IT Manager",
    country: "USA",
    city: "Seattle",
    status: "Active",
    tags: ["enterprise", "tech"],
    createdAt: "2026-07-01",
    updatedAt: "2026-07-22",
  },
  {
    id: "2",
    name: "Sarah Williams",
    company: "Google",
    email: "sarah.williams@google.com",
    phone: "+1 555-2000",
    position: "HR Director",
    country: "USA",
    city: "Mountain View",
    status: "Prospect",
    tags: ["enterprise"],
    createdAt: "2026-07-05",
    updatedAt: "2026-07-21",
  },
  {
    id: "3",
    name: "David Chen",
    company: "Apple",
    email: "david.chen@apple.com",
    phone: "+1 555-3000",
    position: "Senior Engineer",
    country: "USA",
    city: "Cupertino",
    status: "Active",
    tags: ["tech", "hardware"],
    createdAt: "2026-07-08",
    updatedAt: "2026-07-20",
  },
  {
    id: "4",
    name: "Emily Johnson",
    company: "Amazon",
    email: "emily.j@amazon.com",
    phone: "+1 555-4000",
    position: "VP of Operations",
    country: "USA",
    city: "Seattle",
    status: "Active",
    tags: ["enterprise", "ecommerce"],
    createdAt: "2026-07-10",
    updatedAt: "2026-07-19",
  },
  {
    id: "5",
    name: "Michael Brown",
    company: "Tesla",
    email: "m.brown@tesla.com",
    phone: "+1 555-5000",
    position: "Supply Chain Lead",
    country: "USA",
    city: "Austin",
    status: "Inactive",
    tags: ["automotive"],
    createdAt: "2026-06-15",
    updatedAt: "2026-07-18",
  },
  {
    id: "6",
    name: "Lisa Garcia",
    company: "Netflix",
    email: "l.garcia@netflix.com",
    phone: "+1 555-6000",
    position: "Content Strategist",
    country: "USA",
    city: "Los Gatos",
    status: "Active",
    tags: ["media", "entertainment"],
    createdAt: "2026-07-12",
    updatedAt: "2026-07-17",
  },
  {
    id: "7",
    name: "James Wilson",
    company: "Meta",
    email: "j.wilson@meta.com",
    phone: "+1 555-7000",
    position: "Product Manager",
    country: "USA",
    city: "Menlo Park",
    status: "Prospect",
    tags: ["social", "tech"],
    createdAt: "2026-07-14",
    updatedAt: "2026-07-16",
  },
  {
    id: "8",
    name: "Anna Martinez",
    company: "Stripe",
    email: "anna.m@stripe.com",
    phone: "+1 555-8000",
    position: "Finance Lead",
    country: "USA",
    city: "San Francisco",
    status: "Active",
    tags: ["fintech", "payments"],
    createdAt: "2026-07-02",
    updatedAt: "2026-07-15",
  },
  {
    id: "9",
    name: "Robert Taylor",
    company: "Spotify",
    email: "r.taylor@spotify.com",
    phone: "+1 555-9000",
    position: "Data Engineer",
    country: "Sweden",
    city: "Stockholm",
    status: "Blocked",
    tags: ["music", "tech"],
    createdAt: "2026-05-20",
    updatedAt: "2026-07-14",
  },
  {
    id: "10",
    name: "Jennifer Lee",
    company: "Adobe",
    email: "j.lee@adobe.com",
    phone: "+1 555-1100",
    position: "Creative Director",
    country: "USA",
    city: "San Jose",
    status: "Active",
    tags: ["design", "creative"],
    createdAt: "2026-07-06",
    updatedAt: "2026-07-13",
  },
  {
    id: "11",
    name: "Daniel Kim",
    company: "Shopify",
    email: "d.kim@shopify.com",
    phone: "+1 555-2200",
    position: "Developer Relations",
    country: "Canada",
    city: "Ottawa",
    status: "Prospect",
    tags: ["ecommerce", "saas"],
    createdAt: "2026-07-18",
    updatedAt: "2026-07-22",
  },
  {
    id: "12",
    name: "Rachel Green",
    company: "Airbnb",
    email: "rachel.g@airbnb.com",
    phone: "+1 555-3300",
    position: "Hospitality Manager",
    country: "USA",
    city: "San Francisco",
    status: "Active",
    tags: ["travel", "hospitality"],
    notes: "Interested in enterprise plan.",
    createdAt: "2026-07-20",
    updatedAt: "2026-07-22",
  },
];
